# Generated by Django 5.1.4 on 2024-12-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('loan_rate', models.FloatField()),
                ('loan_tenure', models.IntegerField()),
                ('tenure_type', models.CharField(choices=[('Years', 'Years'), ('Months', 'Months')], max_length=10)),
                ('emi', models.FloatField()),
                ('total_interest', models.FloatField()),
                ('total_payment', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
